### PR TITLE
Update to get working with Foundry 0.7.7

### PR DESCRIPTION
**Pull request by chrisesharp**
Thanks for writing this module...it's really useful and solves a problem I particularly had.

Not sure if you are interested, but I took a stab at getting this working with 0.7.7 and it looks like the Ruler API, at least, has changed since you wrote your code so I had to make quite a few changes.

Because I'm installing my copy out of github into Foundry I had to adjust the manifest urls, so please ignore those bits if you accept the PR!

This is for issue #7

### CODE REVIEW

**Comment by Ghilteras** [comment]
@eadorin ^

**Comment by eadorin** [comment]
this is great! I'll update, thank you!

**Comment by Ghilteras** [comment]
@eadorin can you merge this?

**Comment by Ghilteras** [comment]
@eadorin can you merge this?

**Comment by Ghilteras** [comment]
@chrisesharp looks like @eadorin is not interested in working on this module anymore, can you please fork it so we can continue the development there?

**Comment by chrisesharp** [comment]
@Ghilteras I'm not promising to become the new maintainer...@eadorin looked like he was keen to update, and we have just had the Christmas/New Year break, so let's give him a chance.

However, in order to provide the PR I created a fork anyway, so it's already there at https://github.com/chrisesharp/adjusted-movement

**Comment by eadorin** [comment]
Merge confirmed @chrisesharp @Ghilteras

**Pull request merged**
